name: Run Bluesky Bot

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bot Function
        run: |
          curl -X GET "https://bot.videoprivacy.org/.netlify/functions/bot"
