name: Run Bluesky Bot

on:
  schedule:
    # Run every minute - GitHub Actions can have 1-5 minute delays
    - cron: '*/1 * * * *'    
  workflow_dispatch: # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Show current time
        run: |
          echo "Workflow started at: $(date)"
          echo "UTC time: $(date -u)"
      - name: Trigger Bot Function (First Check)
        run: |
          echo "First check at: $(date)"
          curl -X GET "https://bot.videoprivacy.org/.netlify/functions/bot" -w "Response time: %{time_total}s\n"
      - name: Wait 30 seconds
        run: |
          echo "Waiting 30 seconds..."
          sleep 30
      - name: Trigger Bot Function (Second Check)
        run: |
          echo "Second check at: $(date)"
          curl -X GET "https://bot.videoprivacy.org/.netlify/functions/bot" -w "Response time: %{time_total}s\n"
